# Path to sources
#sonar.sources=.
sonar.exclusions=**/Templates/*.cshtml
#sonar.inclusions=

# Path to tests
#sonar.tests=
#sonar.test.exclusions=
#sonar.test.inclusions=

# Source encoding
#sonar.sourceEncoding=UTF-8

# Exclusions for coverage
sonar.coverage.exclusions=**/Program.cs

# Path to coverage reports
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml

# Exclusions for copy-paste detection
sonar.cpd.exclusions=**/CgmLink**.Data/Entities/*.cs,**/CgmLink.Api/Endpoints/**/*Request.cs,**/CgmLink.Api/Endpoints/**/*Response.cs
